version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "blakemorgan"
    target-branch: "dev"

  - package-ecosystem: "github-actions"
    directory: "/" # For GitHub Actions, set the directory to / to check for workflow files in .github/workflows. (GitHub Docs)
    schedule:
      interval: "daily"
    reviewers:
      - "blakemorgan"
    target-branch: "dev"
