---
name: BYU Theme Components
description: BYU themed web components.
resources:
  - src: dist/**
    dest: ./
docs: https://github.com/byuweb/byu-theme-components
type: 'web-component'
preload:
  byu-theme-components.min.js:
  - ./byu-theme-components.min.js
  - lib: shared-icons
    version: latest
    file: logos/monogram-white.svg
  - lib: theme-fonts
    version: latest
    file: ringside/fonts.css
  - lib: theme-fonts
    version: latest
    file: public-sans/fonts.css
