---
name: 2017 Theme Core Components
description: Header and Footer components for 2017 Theme
resources:
  - src: dist/**
    dest: ./
entrypoints:
  2017-core-components.js: 'Examines browser support and downloads the appropriate component bundle'
  2017-core-components.min.js: 'Minified - Examines browser support and downloads the appropriate component bundle'
  2017-core-components.css: 'Main CSS file'
  2017-core-components.min.css: 'Main CSS file'
docs: https://github.com/byuweb/2017-components
