name: Release

on:
  push:
    branches: [ master ]
    paths-ignore:
      - "tests/**"
      - ".git*"
      - "*.md"
      - "index.html"
      - "LICENSE"

env:
  node_version: "14.x"

jobs:
  release:
    name: Release Components
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ env.node_version }}

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: npm ci
        run: npm ci --prefer-offline

      - name: Clean dist folder
        run: npm run clean

      - name: Verify Linting
        run: npm run lint

      - name: Verify Docs
        run: npm run docs

      - name: Verify Build
        run: npm run build

      - name: Get Version Number
        id: version
        run: echo "::set-output name=version::$(npm ls byu-theme-components | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')"

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: Release ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false

